### ISSUE TITLE
some comments and questions.

### ISSUE THREAD

**Issue by wotta** [Tjoosten/project-werk#2]
Just reading through your code and saw that you are adding middleware to your controller.
This could be on your route to make it more readable.

Also, I see you are manually creating a crud routes.
This could be achieved with `Route::resource('articles', 'ArticleController')`.
Also, note you can add an extra route group for the backend namespace.

Just some comments that might help you.

**Comment by Tjoosten** [comment]
I know. But this is an early stage in in development. The first release is all about to get the platform. working. Second release is dedicated on refactoring. Third release building out some small cms. 

But thanks for the intrest and suggestion. 
PS: Help is always welcome.
